### ISSUE TITLE
Cannot install php5.3/php5.4/php5.5/php5.6/php7.0/php7.1 configure: error: Cannot find libz

### ISSUE THREAD

**Issue by huangdijia** [Kyslik/homebrew-php#15]
## Description

brew reinstall -s php53                                                                                                                             

==> Reinstalling kyslik/php/php53
==> Downloading https://php.net/get/php-5.3.29.tar.bz2/from/this/mirror
Already downloaded: /Users/hdj/Library/Caches/Homebrew/downloads/b69147c3d55504dab4a30b96977865deaade52b1b1004c9f2939dc55a4952502--php-5.3.29.tar.bz2
==> Downloading https://gist.githubusercontent.com/javian/6d63097c8c175045aa75ca48a6b8826b/raw/ca7bad287e3af72b83fbb5f7d03186b5da2e65ae/multi-sapi-5.3.29-homebrew.patch
Already downloaded: /Users/hdj/Library/Caches/Homebrew/downloads/2ca18599f2ffd8041a51be966037d07bf99d27c736dc25a87985b5666d7130a2--multi-sapi-5.3.29-homebrew.patch
==> Downloading https://gist.githubusercontent.com/ilovezfs/192a21d13ce0c40dcaa48617f1733097/raw/0856488df0e8190476d64ae68642670aebe8fbb3/gistfile1.txt
Already downloaded: /Users/hdj/Library/Caches/Homebrew/downloads/306b596877b60bac97f2c01e44ad57ec8d7c8318c5614bcfb09f48ea438b5071--gistfile1.txt
==> Patching
==> Applying multi-sapi-5.3.29-homebrew.patch
patching file Makefile.global
patching file Zend/acinclude.m4
patching file Zend/zend_language_parser.y
patching file acinclude.m4
patching file aclocal.m4
patching file configure
patching file configure.in
patching file generated_lists
patching file main/php_config.h.in
patching file sapi/cgi/Makefile.frag
patching file sapi/cgi/config9.m4
patching file sapi/cli/Makefile.frag
patching file sapi/cli/config.m4
patching file sapi/fpm/Makefile.frag
patching file sapi/fpm/config.m4
patching file sapi/litespeed/Makefile.frag
patching file sapi/litespeed/config.m4
patching file sapi/milter/Makefile.frag
patching file sapi/milter/config.m4
==> Applying gistfile1.txt
patching file Zend/zend_API.h
==> ./configure --prefix=/usr/local/Cellar/php53/5.3.29_8 --localstatedir=/usr/local/var --sysconfdir=/usr/local/etc/php/5.3 --with-config-file-path=/usr/local/etc/php/5.3 --w
Last 15 lines from /Users/hdj/Library/Logs/Homebrew/php53/01.configure:
checking for OpenSSL support... yes
checking for Kerberos support... /usr
checking for krb5-config... /usr/bin/krb5-config
checking for DSA_get_default_method in -lssl... no
checking for X509_free in -lcrypto... yes
checking for pkg-config... no
checking for OpenSSL version... >= 0.9.6
checking for CRYPTO_free in -lcrypto... yes
checking for SSL_CTX_set_ssl_version in -lssl... yes
checking for PCRE library to use... bundled
checking whether to enable the SQLite3 extension... yes
checking bundled sqlite3 library... yes
checking for ZLIB support... yes
checking if the location of ZLIB install directory is defined... no
configure: error: Cannot find libz

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/kyslik/homebrew-php/issues

## Context and Logs

Parameter | Value
--------- | ------------------
**macOS version:**       | 10.15.2
**Homebrew version:**   | Homebrew 2.2.0-47-g6decac5
**PHP version in use:** |PHP 7.2.25 (cli)
**Xcode version:**      | Xcode 11.3 Build version 11C24b

**Output of `gcc -v`:**
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 11.0.0 (clang-1100.0.33.15)
Target: x86_64-apple-darwin19.2.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Output of `php -v`:**
PHP 7.2.25 (cli) (built: Nov 22 2019 10:27:28) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.25, Copyright (c) 1999-2018, by Zend Technologies

**Build logs:** _Link to public gist created with `brew gist-logs my-formula`_

https://gist.github.com/e3c9b82d8bb3ace947632a40dc90b440

**Comment by Kyslik** [comment]
I have no clue how to solve this; please use proper way to install PHP now. Sorry.
