### ISSUE TITLE
Brew TAP incomplete

### ISSUE THREAD

**Issue by ddoddsr** [Kyslik/homebrew-php#2]
## Description . attempting to Tap and brew install php70-intl which also fails
Brew TAP incomplete
| => brew tap kyslik/homebrew-php
==> Tapping kyslik/php
Cloning into '/usr/local/Homebrew/Library/Taps/kyslik/homebrew-php'...
remote: Counting objects: 785, done.
remote: Compressing objects: 100% (609/609), done.
remote: Total 785 (delta 532), reused 208 (delta 169), pack-reused 0
Receiving objects: 100% (785/785), 306.03 KiB | 1.21 MiB/s, done.
Resolving deltas: 100% (532/532), done.
Warning: Calling 'depends_on ... => :run' is deprecated!
There is no replacement.
/usr/local/Homebrew/Library/Taps/kyslik/homebrew-php/Formula/php53-mcrypt.rb:19:in `<class:Php53Mcrypt>'
Please report this to the kyslik/php tap!

## Context and Logs

Parameter | Value
--------- | ------------------
**macOS version:**       10.12.6
**Homebrew version:**   Homebrew 1.6.0
    Homebrew/homebrew-core (git revision a8b80; last commit 2018-04-12)
**PHP version in use:** .   PHP 7.0.21 (cli) (built: Jul 10 2017 08:01:11) ( NTS )
**Xcode version:**     Xcode 9.2 .   Build version 9C40b

**Output of `gcc -v`:**
_Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 9.0.0 (clang-900.0.39.2)
Target: x86_64-apple-darwin16.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin_

**Output of `php -v`:**
_result of the CLI output_

**Build logs:** _Link to public gist created with `brew gist-logs my-formula`_

**Comment by Kyslik** [comment]
@ddoddsr I do not maintain this fork, It is just a hack solution, you should use official `homebrew-core` instead.

This fork works **for me** and couple of other people only, I have no clue how to fix your issue, please hunt elsewhere.
