### ISSUE TITLE
error tring to install intl php 7.1 

### ISSUE THREAD

**Issue by jffs** [Kyslik/homebrew-php#3]
## Description

Hey, I want to install php intl extension, but I get these errors 
## Context and Logs

Parameter | Value
--------- | ------------------
**macOS version:**       | 10.13.2
**Homebrew version:**   |Homebrew 1.6.2 . Homebrew/homebrew-core (git revision 53c66; last commit 2018-04-26) 
**PHP version in use:** | _ PHP 7.1.12_
**Xcode version:**      |--
**Output of `gcc -v`:** Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 9.1.0 (clang-902.0.39.1)
Target: x86_64-apple-darwin17.3.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

**Output of `php -v`:**
PHP 7.1.12

**Build logs:** 
==> /usr/local/opt/php71/bin/phpize
==> ./configure --prefix=/usr/local/Cellar/php71-intl/7.1.14_26 --with-php-config=/usr/local/opt/php71/bin/php-config --enable-intl
==> make
Last 15 lines from /Users/macbookpro/Library/Logs/Homebrew/php71-intl/03.make:
#include <php.h>
         ^~~~~~~
1 error generated.
make: *** [intl_convert.lo] Error 1
make: *** Waiting for unfinished jobs....
1 error generated.
make: *** [intl_error.lo] Error 1
1 error generated.
make: *** [php_intl.lo] Error 1
In file included from /private/tmp/php71-intl-20180425-17765-1o8se9g/php-7.1.14/ext/intl/intl_convertcpp.cpp:21:
./intl_convertcpp.h:27:10: fatal error: 'zend_types.h' file not found
#include <zend_types.h>
         ^~~~~~~~~~~~~~
1 error generated.
make: *** [intl_convertcpp.lo] Error 1

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/kyslik/homebrew-php/issues

**Comment by Kyslik** [comment]
Try this: https://github.com/Kyslik/homebrew-php/issues/1#issuecomment-377606835

If that does not help, I am sorry I **do not maintain** this, I just made a fork so I can use it on my own.
