### ISSUE TITLE
php72-trader.rb:18:in  `<class:Php72Trader>'

### ISSUE THREAD

**Issue by yh392261226** [Kyslik/homebrew-php#4]
## Description

_Problem description goes here_

## Context and Logs

Parameter | Value
--------- | ------------------
**macOS version:**       |10.13.4
**Homebrew version:**   |Homebrew 1.6.2-55-gc422737
Homebrew/homebrew-core (git revision fb579f; last commit 2018-05-02)
**PHP version in use:** | PHP 7.2.5
**Xcode version:**      |Xcode 9.3
Build version 9E145

after  brew tap kyslik/php
then：
Warning: Calling 'depends_on ... => :run' is deprecated!
There is no replacement.
/usr/local/Homebrew/Library/Taps/kyslik/homebrew-php/Formula/php72-trader.rb:18:in `<class:Php72Trader>'
Please report this to the kyslik/php tap!

**Comment by yh392261226** [comment]
And the newest swoole extension is 2.1.3 , please update 
thanks

**Comment by Kyslik** [comment]
I am **not maintaining the fork**, please find another solution; this fork is only stepping stone, until homebrew-core works for you.
