### ISSUE TITLE
Error: Calling 'depends on ... => :run' is disabled !

### ISSUE THREAD

**Issue by xavividal** [Kyslik/homebrew-php#6]
## Description

Errors from php70-mcrypto formulae appears everytime I run brew command

### Error output

```
Error: Calling 'depends_on ... => :run' is disabled!
There is no replacement.
/usr/local/Homebrew/Library/Taps/kyslik/homebrew-php/Formula/php70-mcrypt.rb:19:in `<class:Php70Mcrypt>'
Please report this to the kyslik/php tap!
Or, even better, submit a PR to fix it!
```

## Context and Logs

Parameter | Value
--------- | ------------------
**macOS version:**       |  10.13.5
**Homebrew version:**   |  1.7.0
**PHP version in use:** | 7.0.27
**Xcode version:**      | 9.4.1 Build Version 9F2000

**Output of `gcc -v`:**

Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 9.1.0 (clang-902.0.39.2)
Target: x86_64-apple-darwin17.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Output of `php -v`:**

PHP 7.0.27 (cli) (built: Jun 25 2018 10:25:34) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.30, Copyright (c) 1999-2017, by Zend Technologies

**Comment by Kyslik** [comment]
This tap was a workaround for *migration* of original php tap, please use [brew-core](https://github.com/Homebrew/homebrew-core) instead.

**This tap is not maintained.** Good luck!
